/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.TravelAgency;
import Interface.ManageAirliner.AirlinerHomeJPanel;
import Interface.ManageCustomer.CustHomeJPanel;
import Interface.ManageTravelAgency.TravelAgencyHomeJPanel;
import java.awt.CardLayout;

/**
 *
 * @author ankit
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    TravelAgency travelAgency;
    public MainJFrame() {
        initComponents();
        
        travelAgency= new TravelAgency();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        leftJPanel = new javax.swing.JPanel();
        travelAgencyJButton = new javax.swing.JButton();
        manageAirlinerJButton = new javax.swing.JButton();
        manageCustomerJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\MaZhAr\\Pictures\\traveling-ticket-booking-concept-flat-2052886.jpg")); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftJPanel.setBackground(new java.awt.Color(51, 204, 255));
        leftJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        travelAgencyJButton.setBackground(new java.awt.Color(0, 0, 0));
        travelAgencyJButton.setForeground(new java.awt.Color(255, 255, 255));
        travelAgencyJButton.setText("Travel Agency");
        travelAgencyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelAgencyJButtonActionPerformed(evt);
            }
        });
        leftJPanel.add(travelAgencyJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, -1));

        manageAirlinerJButton.setBackground(new java.awt.Color(0, 0, 0));
        manageAirlinerJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageAirlinerJButton.setText("Airliner");
        manageAirlinerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAirlinerJButtonActionPerformed(evt);
            }
        });
        leftJPanel.add(manageAirlinerJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 160, -1));

        manageCustomerJButton.setBackground(new java.awt.Color(0, 0, 0));
        manageCustomerJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageCustomerJButton.setText("Customer");
        manageCustomerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerJButtonActionPerformed(evt);
            }
        });
        leftJPanel.add(manageCustomerJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\MaZhAr\\Pictures\\logoair12.jpeg")); // NOI18N
        leftJPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 220, 260));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\MaZhAr\\Pictures\\logoair14.jpeg")); // NOI18N
        leftJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MaZhAr\\Pictures\\logoair15.jpeg")); // NOI18N
        leftJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jSplitPane1.setLeftComponent(leftJPanel);

        userProcessContainer.setLayout(new java.awt.CardLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\MaZhAr\\Pictures\\Paytm-Travel-Sale.jpg")); // NOI18N
        userProcessContainer.add(jLabel5, "card2");

        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void travelAgencyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelAgencyJButtonActionPerformed
        // TODO add your handling code here:
        
        TravelAgencyHomeJPanel travelPanel= new TravelAgencyHomeJPanel(userProcessContainer,travelAgency );
        userProcessContainer.add("TravelAgencyHomeJPanel",travelPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_travelAgencyJButtonActionPerformed

    private void manageAirlinerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAirlinerJButtonActionPerformed
        // TODO add your handling code here:
        
        AirlinerHomeJPanel airlinerPanel= new AirlinerHomeJPanel(userProcessContainer,travelAgency );
        userProcessContainer.add("AirlinerHomeJPanel",airlinerPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAirlinerJButtonActionPerformed

    private void manageCustomerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerJButtonActionPerformed
        // TODO add your handling code here:
        
        CustHomeJPanel custPanel= new CustHomeJPanel(userProcessContainer,travelAgency );
        userProcessContainer.add("CustHomeJPanel",custPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCustomerJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JButton manageAirlinerJButton;
    private javax.swing.JButton manageCustomerJButton;
    private javax.swing.JButton travelAgencyJButton;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
